theme: jekyll-theme-minimal
title: whoami
logo: [icon.png]
description: server side engineer
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
